//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdgeUninstaller {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EdgeUninstaller.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   agreement.txt file not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AgreementTextFileNotFound {
            get {
                return ResourceManager.GetString("AgreementTextFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You must agree to proceed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConsentRequired {
            get {
                return ResourceManager.GetString("ConsentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option Explicit
        ///Dim objShell, objFSO, strEdgePath
        ///Set objShell = CreateObject(&quot;Shell.Application&quot;)
        ///Set objFSO = CreateObject(&quot;Scripting.FileSystemObject&quot;)
        ///
        ///&apos; Microsoft Edgeのパスを設定
        ///strEdgePath = &quot;C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe&quot;
        ///If Not objFSO.FileExists(strEdgePath) Then
        ///    strEdgePath = &quot;C:\Program Files\Microsoft\Edge\Application\msedge.exe&quot;
        ///End If
        ///
        ///If objFSO.FileExists(strEdgePath) Then
        ///    UnpinFromTaskbar strEdgePath
        ///End If
        ///
        ///Sub UnpinFromTaskbar(strAppPath)
        ///  [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnpinEdge {
            get {
                return ResourceManager.GetString("UnpinEdge", resourceCulture);
            }
        }
    }
}
